from pathlib import Path

from docx import Document


ROOT = Path(r"D:\DesktopApplication")
SOURCE = ROOT / "MudPro-Desktop-App" / "docs" / "MudPro_User_Manual_v1.0.docx"
OUTPUT = (
    ROOT
    / "MudPro-Desktop-App"
    / "docs"
    / "MudPro_User_Manual_English_v1.0.docx"
)


TRANSLATIONS = {
    "Pad setup se daily report generation tak step-by-step guide": "A step-by-step guide from pad setup to daily report generation",
    "MUDPRO+ main workspace: Pad/Well/Report tree aur configuration tabs.": "MUDPRO+ main workspace: Pad/Well/Report tree and configuration tabs.",
    "Software labels English me hain; instructions simple Hinglish me diye gaye hain.": "Software labels and all instructions in this manual are in English.",
    "1. Manual ka purpose aur workflow": "1. Purpose and workflow",
    "2. Interface aur common controls": "2. Interface and common controls",
    "4. Pad, Well aur Report banana": "4. Create a Pad, Well, and Report",
    "5. Report - Well tab": "5. Report - Well tab",
    "6. Report - Mud tab": "6. Report - Mud tab",
    "7. Report - Pump tab": "7. Report - Pump tab",
    "8. Report - Operation tab": "8. Report - Operation tab",
    "9. Report - Pit tab aur balancing": "9. Report - Pit tab and balancing",
    "10. Report - Remarks tab": "10. Report - Remarks tab",
    "11. Save, Lock, Calculate aur Report Generation": "11. Save, Lock, Calculate, and Report Generation",
    "12. Report Manager, Recap aur Utility": "12. Report Manager, Recap, and Utility",
    "13. Common issues aur troubleshooting": "13. Common issues and troubleshooting",
    "Blue section header hai, light-blue column header hai, pale-yellow editable/value area hai, aur gray/white read-only ya calculated area ho sakta hai. Lock state ke hisab se appearance change ho sakti hai.": "Blue indicates a section header, light blue indicates a column header, pale yellow indicates an editable or value area, and gray or white may indicate a read-only or calculated area. The appearance may change according to the lock state.",
    "Ye manual mud engineer, drilling engineer, operator aur reporting team ko MUDPRO+ me master data setup, daily data entry, calculations, pit reconciliation aur report tools use karne me help karta hai.": "This manual helps mud engineers, drilling engineers, operators, and reporting teams use MUDPRO+ for master-data setup, daily data entry, calculations, pit reconciliation, and reporting tools.",
    "Mud Company Setup complete karein.": "Complete Mud Company Setup.",
    "Pad details enter karke save karein.": "Enter and save the Pad details.",
    "Well banayein aur Well/Casing/Interval/Plan/Survey setup karein.": "Create a Well and complete the Well, Casing, Interval, Plan, and Survey setup.",
    "New Report create karein.": "Create a New Report.",
    "Report tabs ko sequence me complete karein: Well -> Mud -> Pump -> Operation -> Pit -> Remarks.": "Complete the Report tabs in sequence: Well -> Mud -> Pump -> Operation -> Pit -> Remarks.",
    "Pit differences aur Storage measured values verify karein.": "Verify pit differences and Storage measured values.",
    "Save, Calculate aur Lock karein; phir next report generate karein.": "Save, Calculate, and Lock the report, then generate the next report.",
    "Report aur operation calculations data-dependent hain. Empty mandatory setup, wrong units, ya unsaved edits calculation ko affect kar sakte hain.": "Report and operation calculations depend on the entered data. Missing mandatory setup, incorrect units, or unsaved edits may affect the calculations.",
    "Figure 1. Home workspace me selected Pad, Well, reports aur configuration tabs.": "Figure 1. Home workspace showing the selected Pad, Well, reports, and configuration tabs.",
    "Report, Utility aur kuch toolbar actions tabhi active hote hain jab valid Pad, Well aur Report selected ho.": "Report, Utility, and some toolbar actions are active only when a valid Pad, Well, and Report are selected.",
    "Home toolbar me Mud Company icon se Company Setup open karein. Engineers, Product, Services, Operator aur Others sections master data define karte hain. Ye data baad me dropdowns aur operation screens me use hota hai.": "Open Company Setup from the Mud Company icon on the Home toolbar. The Engineers, Product, Services, Operator, and Others sections define master data that is later used in dropdowns and operation screens.",
    "Figure 2. Product master: Product, Code, SG, Unit, Group aur pricing fields.": "Figure 2. Product master: Product, Code, SG, Unit, Group, and pricing fields.",
    "Step 1: Editable mode open karein": "Step 1: Enable Editable mode",
    "Top-right Editable control use karein.": "Use the Editable control at the top right.",
    "Step 2: Product data enter karein": "Step 2: Enter product data",
    "Product name, unique Code, SG, unit quantity/class, Group aur price values fill karein.": "Enter the product name, unique Code, SG, unit quantity/class, Group, and price values.",
    "Step 3: Save karein": "Step 3: Save",
    "Bottom Save button ya available global save flow use karein.": "Use the bottom Save button or the available global save workflow.",
    "Step 4: Verify karein": "Step 4: Verify",
    "Product list alphabetic order me visible honi chahiye aur report operations ke dropdown me available honi chahiye.": "The product list should appear in alphabetical order and be available in the report operation dropdowns.",
    "Figure 3. Package, Services aur Engineering master sections.": "Figure 3. Package, Services, and Engineering master sections.",
    "Package me Name, Code, Unit aur Price define karein.": "Define the Name, Code, Unit, and Price in Package.",
    "Services aur Engineering items ko unke relevant section me enter karein.": "Enter Services and Engineering items in their relevant sections.",
    "Existing row par right-click karke available edit/delete actions use karein.": "Right-click an existing row to use the available edit or delete actions.",
    "Delete action successful hone par item database aur UI dono se remove hona chahiye.": "After a successful delete action, the item should be removed from both the database and the UI.",
    "Engineer/operator names aur contact details clean, unique format me rakhein.": "Keep engineer/operator names and contact details in a clean, unique format.",
    "Units, activities, mud types aur supporting lookup values ko Others me maintain karein.": "Maintain units, activities, mud types, and supporting lookup values in Others.",
    "Master data change ke baad affected report dropdown ko refresh/reopen karein.": "Refresh or reopen the affected report dropdown after changing master data.",
    "Figure 4. Pad tab, left report tree aur top-level setup tabs.": "Figure 4. Pad tab, report tree on the left, and top-level setup tabs.",
    "Step 1: Pad select/create karein": "Step 1: Select or create a Pad",
    "Left tree me Pad select karein. Required details complete kiye bina Well creation enabled nahi hoga.": "Select the Pad in the left tree. Well creation remains disabled until the required Pad details are complete.",
    "Step 2: Location choose karein": "Step 2: Choose the location",
    "Land ya Offshore select karein.": "Select Land or Offshore.",
    "Step 3: Pad fields fill karein": "Step 3: Complete the Pad fields",
    "Field/Block, Rig, location, stock point, phone, operator, contractor aur representative fields enter karein.": "Enter the Field/Block, Rig, location, stock point, phone, operator, contractor, and representative fields.",
    "Optional client logo aur memo add karein.": "Optionally add a client logo and memo.",
    "Top toolbar Save se Pad data save karein.": "Save the Pad data using Save on the top toolbar.",
    "PAD, INVENTORY, PIT, PUMP, SCE, FORMATION, REPORT aur ALERT configuration Pad/Well context ke liye use hote hain.": "PAD, INVENTORY, PIT, PUMP, SCE, FORMATION, REPORT, and ALERT are used to configure the Pad/Well context.",
    "Figure 5. Well setup tabs: Well, Casing, Interval, Plan aur Survey.": "Figure 5. Well setup tabs: Well, Casing, Interval, Plan, and Survey.",
    "Step 1: New Well click karein": "Step 1: Click New Well",
    "Completed Pad selected hone par toolbar ka New Well button active hota hai.": "The New Well toolbar button becomes active when a completed Pad is selected.",
    "Step 2: Basic fields enter karein": "Step 2: Enter the basic fields",
    "Well Name, API Well No. aur Spud Date fill karke Create karein.": "Enter the Well Name, API Well No., and Spud Date, then click Create.",
    "Step 3: Well tab complete karein": "Step 3: Complete the Well tab",
    "Location/reference values aur units verify karein.": "Verify the location/reference values and units.",
    "Step 4: Casing define karein": "Step 4: Define the Casing",
    "Description, Type, OD, Weight, ID, Top, Shoe aur Bit data enter karein.": "Enter the Description, Type, OD, Weight, ID, Top, Shoe, and Bit data.",
    "Step 5: Interval/Plan/Survey complete karein": "Step 5: Complete Interval, Plan, and Survey",
    "Hole interval, mud plan, depth plan aur survey stations maintain karein.": "Maintain the hole interval, mud plan, depth plan, and survey stations.",
    "Well/Casing/Pit configuration operational master setup hai. Data ko intentional delete action ke bina remove nahi karna chahiye.": "Well, Casing, and Pit configuration is operational master setup. This data should remain saved until it is intentionally deleted.",
    "Step 1: Well select karein": "Step 1: Select the Well",
    "Left tree me active Well select karein.": "Select the active Well in the left tree.",
    "Step 2: New Report click karein": "Step 2: Click New Report",
    "Toolbar me document icon se next report create karein.": "Create the next report using the document icon on the toolbar.",
    "Step 3: Report select karein": "Step 3: Select the Report",
    "Left tree me timestamp/report number wali new report row select karein.": "Select the new report row with its timestamp/report number in the left tree.",
    "Step 4: Carry-over decide karein": "Step 4: Choose whether to carry data over",
    "Previous report ka setup/data chahiye to Carry-over use karein; confirmation message dhyan se padhein.": "Use Carry-over when setup or data from the previous report is required. Read the confirmation message carefully.",
    "Figure 6. Report Well tab ke main sections.": "Figure 6. Main sections of the Report Well tab.",
    "Well tab daily drilling context define karta hai. Is tab ke values downstream hole volume, hydraulics, pit volume aur report summaries ko affect karte hain.": "The Well tab defines the daily drilling context. Its values affect downstream hole-volume, hydraulics, pit-volume, and report-summary calculations.",
    "Hole volume ke liye casing/open-hole geometry, MD aur drill-string OD/ID/length complete hona zaroori hai.": "Casing/open-hole geometry, MD, and drill-string OD, ID, and length must be complete for hole-volume calculations.",
    "Nozzle row update karne ke baad TFA change verify karein aur report generate karne se pehle Save karein.": "After updating a Nozzle row, verify the TFA change and save before generating the report.",
    "Mud tab me Mud Properties, Rheology Model, rheology readings, Specific Gravity aur Solids enter kiye jate hain.": "Use the Mud tab to enter Mud Properties, the Rheology Model, rheology readings, Specific Gravity, and Solids.",
    "Sample details, temperatures, depth, MW, funnel viscosity aur relevant chemical/physical properties enter karein.": "Enter sample details, temperatures, depth, MW, funnel viscosity, and the relevant chemical and physical properties.",
    "Step 2: Rheology Model select karein": "Step 2: Select the Rheology Model",
    "Available model, jaise Bingham, select karein.": "Select an available model, such as Bingham.",
    "600/300/200/100/6/3 RPM readings aur calculated PV/YP verify karein.": "Enter the 600/300/200/100/6/3 RPM readings and verify the calculated PV/YP.",
    "Oil/HGS/LGS aur shale/bentonite CEC values enter karein.": "Enter the Oil/HGS/LGS and shale/bentonite CEC values.",
    "Units aur decimal format verify karke Save karein.": "Verify the units and decimal format, then save.",
    "Mud weight, viscosity aur concentration units Options me configured units se match hone chahiye.": "Mud weight, viscosity, and concentration units must match the units configured in Options.",
    "Figure 7. Pump, Summary, Shaker aur Other SCE sections.": "Figure 7. Pump, Summary, Shaker, and Other SCE sections.",
    "Step 1: Configured equipment choose karein": "Step 1: Choose configured equipment",
    "Pad PUMP/SCE setup me available equipment dropdown se select karein.": "Select the equipment from the dropdown populated by the Pad PUMP/SCE setup.",
    "Step 2: Operating inputs enter karein": "Step 2: Enter operating inputs",
    "Stroke, screen, flow aur time values fill karein.": "Enter the stroke, screen, flow, and time values.",
    "Step 3: Calculated outputs verify karein": "Step 3: Verify calculated outputs",
    "Displacement/rate/summary values expected range me hone chahiye.": "The displacement, rate, and summary values should be within the expected range.",
    "Step 4: Save karein": "Step 4: Save",
    "Pump tab leave karne ya report generate karne se pehle save complete hone dein.": "Allow saving to finish before leaving the Pump tab or generating a report.",
    "Operation tab daily material aur mud movements record karta hai. Left operation menu me row select karke operation choose karein. Har operation apna independent data rakhta hai; unrelated operation values merge nahi honi chahiye.": "The Operation tab records daily material and mud movements. Select a row in the left operation menu and choose an operation. Each operation stores independent data; values from unrelated operations must not be merged.",
    "Figure 8. Consume Product table, distribution aur Add Water controls.": "Figure 8. Consume Product table, distribution, and Add Water controls.",
    "Inventory list se one or more products choose karein.": "Choose one or more products from the inventory list.",
    "Used ya Final method select karein.": "Select the Used or Final input method.",
    "Step 3: Usage enter karein": "Step 3: Enter usage",
    "Initial, Adjust aur Used/Final values fill karein; Cost aur Vol (bbl) verify karein.": "Enter the Initial, Adjust, and Used/Final values, then verify Cost and Vol (bbl).",
    "Active System ya selected pit ko calculated volume distribute karein.": "Distribute the calculated volume to Active System or the selected pit.",
    "Operation tab ke save/calculate flow se product rows aur distribution save karein.": "Save the product rows and distribution using the Operation tab save/calculate workflow.",
    "Previous report ka Final, same product select karne par next report ka Initial banta hai.": "For the same selected product, the previous report's Final value becomes the next report's Initial value.",
    "Figure 9. Return Product me BOL, Product aur Package sections.": "Figure 9. BOL, Product, and Package sections in Return Product.",
    "BOL number enter karein.": "Enter the BOL number.",
    "Product/Package select karke quantity/unit details complete karein.": "Select a Product or Package and complete the quantity and unit details.",
    "Return All Inventory sirf intentional full-return case me use karein.": "Use Return All Inventory only for an intentional full return.",
    "Save ke baad inventory balance verify karein.": "Verify the inventory balance after saving.",
    "Premixed Mud applicable ho to checkbox aur source select karein.": "If Premixed Mud applies, select the checkbox and source.",
    "From, To, returned/lost volume, MW, Mud Type, BOL aur cost values enter karein.": "Enter From, To, returned/lost volume, MW, Mud Type, BOL, and cost values.",
    "Leased status applicable ho to checkbox use karein.": "Select the checkbox if the Leased status applies.",
    "Pit tab physical pit measurements ko calculated report volume se reconcile karta hai. Is tab ko report closeout se pehle zaroor verify karein.": "The Pit tab reconciles physical pit measurements with the calculated report volume. Always verify this tab before report closeout.",
    "End Vol. - Active System batata hai ki pit adjustment abhi pending hai.": "End Vol. - Active System shows the pit adjustment that is still pending.",
    "Pit adjustment ke baad End Vol. aur Active System equal hone chahiye; pending difference 0 hona chahiye.": "After the pit adjustment, End Vol. and Active System should be equal, and the pending difference should be 0.",
    "Positive pending: required amount kisi active pit me add karein.": "Positive pending amount: add the required amount to an active pit.",
    "Negative pending: required amount kisi active pit se reduce karein.": "Negative pending amount: reduce an active pit by the required amount.",
    "Pit capacity se zyada measured volume enter nahi karein.": "Do not enter a measured volume greater than the pit capacity.",
    "Adjustment current report me hona chahiye; previous report values ko unintentionally modify nahi karein.": "Make the adjustment in the current report; do not unintentionally modify previous-report values.",
    "Storage me Calculated Vol aur Measured Vol equal hone par report normal generate hoti hai. Missing/different value par confirmation popup aata hai. Yes se report continue hoti hai; No se generation cancel hoti hai.": "When Calculated Vol and Measured Vol are equal in Storage, the report is generated normally. If a value is missing or different, a confirmation dialog appears. Select Yes to continue or No to cancel report generation.",
    "Hole Volume (bbl) me String, Annulus, Below bit, Hole aur Displacement review karein.": "In Hole Volume (bbl), review String, Annulus, Below bit, Hole, and Displacement.",
    "Displacement drill-string geometry ke OD volume aur ID/internal volume difference se calculate hota hai.": "Displacement is calculated from the difference between the drill-string OD volume and ID/internal volume.",
    "Active Pits/Storage distribution aur product concentration values verify karein.": "Verify Active Pits/Storage distribution and product concentration values.",
    "Step 1: Relevant text enter karein": "Step 1: Enter relevant text",
    "Clear, factual aur time-specific statements use karein.": "Use clear, factual, and time-specific statements.",
    "Supported attachment control available ho to evidence/document attach karein.": "Attach evidence or a document when a supported attachment control is available.",
    "Tab leave karne ya report lock karne se pehle Save karein.": "Save before leaving the tab or locking the report.",
    "Top global Save current active module ke latest edits persist karta hai.": "The top global Save control persists the latest edits in the active module.",
    "Cell edit ke turant baad tab switch/report generation na karein jab saving indicator active ho.": "Do not switch tabs or generate a report immediately after editing a cell while the saving indicator is active.",
    "Master setup aur report data alag scopes me save hote hain.": "Master setup and report data are saved in separate scopes.",
    "Unlock state me editable fields active hote hain.": "Editable fields are active in the unlocked state.",
    "Lock state accidental edits prevent karta hai.": "The locked state prevents accidental edits.",
    "Final review ke baad report lock karein.": "Lock the report after the final review.",
    "Current tab calculations refresh karta hai.": "Refreshes calculations for the current tab.",
    "Calculated values ko source inputs aur units ke against verify karein.": "Verify calculated values against the source inputs and units.",
    "Red error panel, overflow warning, missing mandatory selection ya failed save message visible ho to report generation se pehle issue resolve karein.": "If a red error panel, overflow warning, missing mandatory selection, or failed-save message is visible, resolve the issue before generating the report.",
    "Figure 11. Report Manager search criteria aur result area.": "Figure 11. Report Manager search criteria and result area.",
    "Step 1: Current Well choose karein": "Step 1: Choose the Current Well",
    "Dropdown me required Well select karein.": "Select the required Well from the dropdown.",
    "Step 2: Criteria enable karein": "Step 2: Enable criteria",
    "Date, Report No., Depth, MW ya text filters ke checkbox select karein.": "Select the checkboxes for Date, Report No., Depth, MW, or text filters.",
    "Step 3: Search karein": "Step 3: Search",
    "Search button se matching reports load karein.": "Use Search to load matching reports.",
    "Required report select/open karein; delete sirf authorized case me.": "Select or open the required report. Delete a report only when authorized.",
    "Well Comparison: selected wells/reports ka comparison.": "Well Comparison: compares selected wells and reports.",
    "Recap: report data ka summarized analytical view.": "Recap: provides a summarized analytical view of report data.",
    "Cost of Pad: Pad-level cost view.": "Cost of Pad: provides a Pad-level cost view.",
    "Engineering Tools: hydraulics/rheology related calculations.": "Engineering Tools: provides hydraulics- and rheology-related calculations.",
    "Unit Conversion: source value/unit se target unit conversion.": "Unit Conversion: converts a source value and unit to a target unit.",
    "Software calculation engineering judgment ka replacement nahi hai. Input quality, selected model aur unit system verify karna user ki responsibility hai.": "Software calculations do not replace engineering judgment. The user is responsible for verifying input quality, the selected model, and the unit system.",
    "Support ko kya dena hai": "Information to provide to Support",
    "Pad name, Well name aur Report number.": "Pad name, Well name, and Report number.",
    "Exact tab/section/operation name.": "Exact tab, section, or operation name.",
    "Expected result aur actual result.": "Expected result and actual result.",
    "Issue reproduce karne ke exact steps.": "Exact steps required to reproduce the issue.",
    "Backend/server log ka relevant timestamp, agar available ho.": "Relevant backend/server log timestamp, if available.",
    "Report generate karne se pehle data completeness, units, pit balance aur save status ko ek baar visually verify karein.": "Before generating a report, visually verify data completeness, units, pit balance, and save status.",
    "Pad, Well, Inventory, Pit, Pump, SCE, Formation, Report aur Alert configuration.": "Configures Pad, Well, Inventory, Pit, Pump, SCE, Formation, Report, and Alert.",
    "Report Manager, Well Comparison, Recap aur Cost of Pad.": "Provides Report Manager, Well Comparison, Recap, and Cost of Pad.",
    "Engineering Tools aur Unit Conversion.": "Provides Engineering Tools and Unit Conversion.",
    "User Manual, About, Disclaimer aur Abbreviation.": "Provides User Manual, About, Disclaimer, and Abbreviation.",
    "Selected and completed Pad ke andar new Well banata hai.": "Creates a new Well inside the selected, completed Pad.",
    "Selected Well ke liye next report create karta hai.": "Creates the next report for the selected Well.",
    "Saved/exported files location open karta hai.": "Opens the saved/exported files location.",
    "Current active section ka latest data save karta hai.": "Saves the latest data in the active section.",
    "Current data ki separate copy/export flow ke liye.": "Creates a separate copy or starts an export workflow for the current data.",
    "Previous report data ko selected report me carry forward karta hai.": "Carries previous-report data into the selected report.",
    "Report editing enable/disable karta hai.": "Enables or disables report editing.",
    "Current tab ke calculation/save workflow ko execute karta hai.": "Executes the calculation/save workflow for the current tab.",
    "Units aur application options.": "Configures units and application options.",
    "Company master-data setup open karta hai.": "Opens Company master-data setup.",
    "Report no., date/time, engineers, representatives, activity, MD/TVD, inclination, drilling parameters aur temperatures.": "Report number, date/time, engineers, representatives, activity, MD/TVD, inclination, drilling parameters, and temperatures.",
    "Current casing description, OD, ID, top, shoe aur length.": "Current casing description, OD, ID, top, shoe, and length.",
    "Hole description, ID, MD aur washout percentage.": "Hole description, ID, MD, and washout percentage.",
    "Manufacturer/type, bit count, size aur depth-in.": "Manufacturer/type, bit count, size, and depth-in.",
    "Nozzle count aur size (1/32 in); TFA automatically calculate hota hai.": "Nozzle count and size (1/32 in); TFA is calculated automatically.",
    "Description, OD, weight, ID, grade aur length. Total Length verify karein.": "Description, OD, weight, ID, grade, and length. Verify Total Length.",
    "Daily activities aur minutes.": "Daily activities and minutes.",
    "Model/type, liner ID, rod OD, stroke length, efficiency, displacement, stroke rate aur flow rate.": "Model/type, liner ID, rod OD, stroke length, efficiency, displacement, stroke rate, and flow rate.",
    "Shaker/model, screen values, operating time aur OOC weight.": "Shaker/model, screen values, operating time, and OOC weight.",
    "Other solids-control equipment, model, U/F, O/F, time aur OOC weight.": "Other solids-control equipment, model, U/F, O/F, time, and OOC weight.",
    "Package, service aur engineering usage record.": "Records Package, Service, and Engineering usage.",
    "Inventory product usage, cost aur volume addition.": "Records inventory product usage, cost, and volume addition.",
    "Product/package inventory receive karna.": "Receives Product or Package inventory.",
    "Product/package inventory return karna.": "Returns Product or Package inventory.",
    "Pits/systems ke beech mud transfer.": "Transfers mud between pits or systems.",
    "BOL ke against premixed mud receive karna.": "Receives premixed mud against a BOL.",
    "Returned ya lost mud transaction.": "Records a returned or lost mud transaction.",
    "Selected system me water volume add karna.": "Adds water volume to the selected system.",
    "Active system dump ya storage transfer.": "Dumps the Active System or transfers it to Storage.",
    "Pit-wise measured volume, MW aur mud selection.": "Pit-wise measured volume, MW, and mud selection.",
    "Calculated volume aur measured volume comparison.": "Compares calculated volume and measured volume.",
    "Hole, Active Pits, Active System, End Vol. aur pending difference.": "Shows Hole, Active Pits, Active System, End Vol., and pending difference.",
    "Loads, volume, weight, oil/water/solids aur OOC weight.": "Shows loads, volume, weight, oil/water/solids, and OOC weight.",
    "Hole volume, pit distribution aur concentration snapshot.": "Shows hole volume, pit distribution, and concentration snapshot.",
    "Next tour/team ke liye recommended treatment.": "Recommended treatment for the next tour or team.",
    "Current operation ki important observations.": "Important observations for the current operation.",
    "Report recap/general remarks.": "Report recap and general remarks.",
    "Internal-only notes; external distribution se pehle review karein.": "Internal-only notes; review them before external distribution.",
    "Pad, Well aur Report selection complete karein.": "Complete the Pad, Well, and Report selection.",
    "Company Setup/Inventory master data save hua hai ya nahi check karein; refresh/reopen karein.": "Confirm that Company Setup/Inventory master data has been saved, then refresh or reopen the screen.",
    "Current report selected hai ya nahi verify karein; field edit ke baad Save complete hone dein.": "Verify that the current report is selected and allow Save to finish after editing a field.",
    "Required geometry, unit, depth, volume aur selection inputs missing ho sakte hain.": "Required geometry, unit, depth, volume, or selection inputs may be missing.",
    "Active Pits ko positive/negative pending amount ke according adjust karein.": "Adjust Active Pits according to the positive or negative pending amount.",
    "Storage calculated vs measured volumes compare karein; intentional mismatch ho tabhi Yes choose karein.": "Compare Storage calculated and measured volumes. Choose Yes only when the mismatch is intentional.",
    "Network, backend/API availability aur selected Well/Report context check karein.": "Check the network, backend/API availability, and selected Well/Report context.",
    "Current action stop karein, screenshot/error text capture karein aur support ko report karein.": "Stop the current action, capture the screenshot or error text, and report it to Support.",
    "Window maximize karein; supported display scaling/resolution use karein.": "Maximize the window and use a supported display scaling and resolution.",
    "Correct Pad, Well aur latest Report selected.": "Correct Pad, Well, and latest Report selected.",
    "Pump Rate, Pump Pressure aur Downhole Tools Pressure Loss.": "Pump Rate, Pump Pressure, and Downhole Tools Pressure Loss.",
    "Old value reload ho rahi hai": "The old value is being reloaded.",
    "Data load nahi ho raha": "The data is not loading.",
}


def all_paragraphs(document):
    yield from document.paragraphs
    for section in document.sections:
        yield from section.header.paragraphs
        yield from section.footer.paragraphs
    for table in document.tables:
        for row in table.rows:
            for cell in row.cells:
                yield from cell.paragraphs


def translate_document():
    document = Document(SOURCE)
    translated = 0
    for paragraph in all_paragraphs(document):
        for run in paragraph.runs:
            replacement = TRANSLATIONS.get(run.text)
            if replacement is not None:
                run.text = replacement
                translated += 1

    document.core_properties.title = "MUDPRO+ User Manual - English"
    document.core_properties.subject = "English desktop software operator guide"
    document.core_properties.language = "en-US"
    document.save(OUTPUT)
    print(f"Translated runs: {translated}")
    print(OUTPUT)


if __name__ == "__main__":
    translate_document()
